apiVersion: v1
kind: Secret
metadata:
  name: nodejs-app-secret
  namespace: devops-exercise
type: Opaque
stringData:
  # Add any sensitive data here
  # For production, use sealed-secrets or external secret management
  API_KEY: "your-api-key-here"
  JWT_SECRET: "your-jwt-secret-here"