apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-app-config
  namespace: devops-exercise
data:
  NODE_ENV: "production"
  PORT: "8000"
  LOG_LEVEL: "info"
  # Configuraci贸n de base de datos
  DB_TYPE: "sqlite"
  DB_NAME: "production.sqlite"
  # Configuraci贸n de la aplicaci贸n
  APP_NAME: "Devsu DevOps Node.js Demo"
  API_PREFIX: "/api"
  # Configuraci贸n de health check
  HEALTH_CHECK_INTERVAL: "30000"
  HEALTH_CHECK_TIMEOUT: "3000"